### ISSUE TITLE
Login/Register Pages

### ISSUE THREAD

**Issue by GPropersi** [The-Rubber-Ducks/CharitableGaming#8]
Pages that let a user login and register, as well as visible functionality for logging out.

**Comment by jawkha** [comment]
My understanding is that this issue can be completed in the following way:
- Build a login form
- Build a registration/signup form
- Build a navigation menu (nav-bar) at the extreme right of which the user should see links according to the following logic:
If the user is not already logged in, they should see a link which says "Log in", clicking which should take the user to the login page.
If the user is already logged in, they should see an avatar/icon clicking which will display a dropdown menu that has the following two components:
1. A link which says Profile and clicking which takes the user to their profile page.
2. A link which says Log out and clicking which logs the user out and takes them back to the home page.
